import {DEFINITIONS,BY_ID,DEFAULT_GOALS,dayKey} from './nutrition.js';
import {validateAnalysis,safeSourceURL} from './claude.js';
const assert=(v,message)=>{if(!v)throw new Error('バックアップが不正です：'+message);};
const obj=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const finite=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=1e8;
const text=v=>typeof v==='string'&&v.length<=5000;
function exact(v,keys){assert(obj(v),'オブジェクト形式');assert(Object.keys(v).every(k=>keys.includes(k)),'未対応の項目');assert(keys.every(k=>k in v),'必須項目');}
export function validateGoals(goals){assert(obj(goals),'栄養目標');assert(Object.keys(goals).length===Object.keys(DEFAULT_GOALS).length,'栄養目標の数');for(const [id,base] of Object.entries(DEFAULT_GOALS)){const g=goals[id];exact(g,base.upper?['mode','target','upper']:['mode','target']);assert(g.mode===base.mode&&finite(g.target)&&g.target>0,'目標値');if(base.upper)assert(finite(g.upper)&&g.upper>=g.target,'目標の範囲');if(['fat','saturatedFat','carbohydrate'].includes(id))assert(g.target<=100&&(!g.upper||g.upper<=100),'エネルギー比率');}return goals;}
export function validateBackup(data){exact(data,['schemaVersion','exportedAt','settings','nutrientGoals','products','productVersions','intakeLogs','foodDatabaseVersion']);assert([1,2].includes(data.schemaVersion),'未対応のバージョン');assert(text(data.exportedAt)&&Number.isFinite(Date.parse(data.exportedAt)),'書出日時');exact(data.settings,['model','structuredOutput']);assert(text(data.settings.model)&&/^claude-[a-z0-9-]+$/.test(data.settings.model),'モデル');assert(typeof data.settings.structuredOutput==='boolean','解析設定');validateGoals(data.nutrientGoals);assert(text(data.foodDatabaseVersion),'食品成分表のバージョン');for(const s of ['products','productVersions','intakeLogs'])assert(Array.isArray(data[s])&&data[s].length<=100000,'記録の配列');const products=new Set(),versions=new Map(),logs=new Set();
 for(const p of data.products){exact(p,['id','name','manufacturer','createdAt']);assert(text(p.id)&&p.id&&!products.has(p.id)&&text(p.name)&&text(p.manufacturer)&&text(p.createdAt)&&Number.isFinite(Date.parse(p.createdAt)),'商品');products.add(p.id);}
 for(const v of data.productVersions){exact(v,['id','productId','createdAt','analysis','foodDatabaseVersion']);assert(text(v.id)&&v.id&&!versions.has(v.id)&&products.has(v.productId)&&text(v.createdAt)&&Number.isFinite(Date.parse(v.createdAt))&&text(v.foodDatabaseVersion),'商品バージョン');validateAnalysis(v.analysis);versions.set(v.id,v.productId);}
 for(const l of data.intakeLogs){exact(l,['id','productId','productVersionId','name','consumedAt','dayKey','amount','nutrientSnapshot']);assert(text(l.id)&&l.id&&!logs.has(l.id)&&versions.get(l.productVersionId)===l.productId&&text(l.name),'食事記録の参照');assert(text(l.consumedAt)&&Number.isFinite(Date.parse(l.consumedAt))&&l.dayKey===dayKey(l.consumedAt),'日本時間の日付');exact(l.amount,['value','unit']);assert(finite(l.amount.value)&&l.amount.value>0&&['g','ml','piece','package'].includes(l.amount.unit),'摂取量');assert(obj(l.nutrientSnapshot)&&Object.keys(l.nutrientSnapshot).length===DEFINITIONS.length,'栄養スナップショット');for(const d of DEFINITIONS){const n=l.nutrientSnapshot[d.id];assert(obj(n)&&Object.keys(n).every(k=>['value','unit','source','confidence','foodIds','origin','sourceUrl','sourceTitle'].includes(k)),'栄養値の形式');assert(n.unit===d.unit&&(n.value===null||finite(n.value))&&[null,'declared','calculated','estimated','published'].includes(n.source)&&(n.confidence===null||finite(n.confidence)&&n.confidence<=1),'栄養値');assert(n.value===null?n.source===null:n.source!==null,'栄養値の由来');if(n.origin!==undefined)assert(n.origin==='published','公式値の由来');if(n.sourceUrl!==undefined)assert(safeSourceURL(n.sourceUrl),'出典URL');if(n.sourceTitle!==undefined)assert(text(n.sourceTitle),'出典名');if(n.source==='published'||n.origin==='published')assert(safeSourceURL(n.sourceUrl),'公式値の出典');if(n.foodIds!==undefined)assert(Array.isArray(n.foodIds)&&n.foodIds.every(id=>id===null||text(id)),'食品ID');}logs.add(l.id);}
 return data;
}
export function createBackup(state,settings,goals,version){const data={schemaVersion:2,exportedAt:new Date().toISOString(),settings:{model:settings.model,structuredOutput:settings.structuredOutput},nutrientGoals:structuredClone(goals),products:structuredClone(state.products),productVersions:structuredClone(state.productVersions),intakeLogs:structuredClone(state.intakeLogs),foodDatabaseVersion:version};return validateBackup(data);}
export async function readBackup(file){if(file.size>50*1024*1024)throw new Error('バックアップは50MB以下にしてください。');let data;try{data=JSON.parse(await file.text());}catch{throw new Error('JSONファイルを読み取れませんでした。');}return validateBackup(data);}
export function downloadBackup(data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hitosaji-'+dayKey()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export async function exportBackup(data){
 const file=new File([JSON.stringify(data,null,2)],'hitosaji-'+dayKey()+'.json',{type:'application/json'});
 if(navigator.share&&navigator.canShare?.({files:[file]})){
  try{await navigator.share({files:[file],title:'ひとさじ バックアップ'});return {exported:true,method:'share'};}
  catch(e){if(e.name==='AbortError')return {exported:false,method:'cancelled'};throw new Error('共有できませんでした。「ダウンロードで書き出す」を使ってください。');}
 }
 downloadBackup(data);return {exported:true,method:'download'};
}
