import {storageStatus,backupDue} from './storage.js';
import {DEFINITIONS,DEFAULT_GOALS,DEFAULT_SETTINGS,dayKey,daysBack,fmt,normalizeUnit,goalFor,statusOf,snapshot,aggregate,versionFingerprint,majorChange,isDuplicate} from './nutrition.js';
import * as db from './db.js';
import {hasKey,setKey,deleteKey,analyze,resizePhoto,validateAnalysis} from './claude.js';
import {createBackup,downloadBackup,exportBackup,readBackup,validateGoals} from './backup.js';
import {foodAnalysis,recommend} from './recommendations.js';
import {h,safe,btn,link,card,note,label,number,inputValue,title,empty,pill,toast,ask,dialog,dialogBody} from './ui.js';
const app=document.querySelector('#app');
let state,settings,goals,foodDB,foods=[],route='home',capture=null,analysis=null,amount=null,consumedAt=null,analyzing=false,saving=false,historyDays=7,filter='all';
let persistence={state:'checking',label:'保存状態を確認しています'};
const units={g:'g',ml:'ml',piece:'個',package:'包装・皿'};
const amountText=a=>fmt(a.value)+' '+units[a.unit],stamp=()=>new Date().toISOString(),todayLogs=()=>state.intakeLogs.filter(l=>l.dayKey===dayKey());
const localTime=iso=>dayKey(iso)+'T'+new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));
async function refresh(){state=await db.readState();settings={...DEFAULT_SETTINGS,...state.settings.find(s=>s.id==='preferences')};goals=structuredClone(state.settings.find(s=>s.id==='goals')?.value||DEFAULT_GOALS);}
function render(){if(!state||!foodDB)return;route=analyzing?'capture':(location.hash.slice(1)||'home').split('/')[0];document.querySelectorAll('[data-nav]').forEach(el=>el.classList.toggle('active',el.dataset.nav===route));document.querySelector('#connection').textContent=navigator.onLine?'この端末に保存':'オフライン';const pages={home:homeView,capture:captureView,review:reviewView,history:historyView,settings:settingsView,nutrients:nutrientsView,recommend:recommendView,foods:foodsView};app.replaceChildren(...(pages[route]||homeView)().filter(Boolean));}
const navigate=hash=>{if(location.hash==='#'+hash)render();else location.hash=hash;};
function nutrientRow(d,total){
 const n=total[d.id],s=statusOf(d.id,n.value,goals),g=goalFor(d.id,goals);
 const percentage=s.ratio===null?'—':fmt(s.ratio*100,0)+'%'+(g?.mode==='maximum'?'（上限比）':g?.mode==='range'?'（下限比）':'');
 const target=!g?'目標なし':g.mode==='range'?fmt(g.target)+'〜'+fmt(g.upper)+' '+d.unit:(g.mode==='maximum'?'上限 ':'目標 ')+fmt(g.target)+' '+d.unit;
 const row=h('div',{class:'nutrient'},h('div',{class:'nutrient-line'},h('strong',{},d.label),h('span',{},percentage)),h('p',{class:'muted'},fmt(n.value)+' '+d.unit+' / '+target));
 if(g){const bar=h('div',{class:'bar',role:'meter','aria-label':d.label+' '+percentage,'aria-valuemin':0,'aria-valuemax':100,'aria-valuenow':s.ratio===null?null:Math.min(100,s.ratio*100)},h('span'));bar.firstChild.style.width=Math.min(100,(s.ratio||0)*100)+'%';if(['high','near'].includes(s.kind))bar.firstChild.style.background='var(--orange)';row.append(bar);}
 row.append(h('small',{class:'muted'},[g?s.label:'参考値',n.partial?'判明分のみ・一部不明':'',n.estimated?'推定を含む':''].filter(Boolean).join(' ・ ')));return row;
}
const backupDate=()=>state.settings.find(s=>s.id==='backupStatus')?.lastExportAt;
async function writeBackup(download=false){
 const data=createBackup(state,settings,goals,foodDB.sourceVersion);
 const result=download?(downloadBackup(data),{exported:true,method:'download'}):await exportBackup(data);
 if(!result.exported){toast('書き出しをキャンセルしました');return;}
 await db.put('settings',{id:'backupStatus',lastExportAt:data.exportedAt});await refresh();render();
 toast(result.method==='share'?'共有に渡しました。保存先にJSONがあることを確認してください。':'書き出しました。ダウンロード先にJSONがあることを確認してください。');
}
function backupReminder(){return backupDue(state.intakeLogs,backupDate())?note(h('div',{class:'stack'},h('strong',{},'食事記録をバックアップしましょう'),h('span',{},backupDate()?'前回の書き出しから7日以上経過しています。':'まだバックアップを書き出していません。'),btn('バックアップを書き出す',()=>writeBackup(),'primary'))):null;}
function sourceNotes(a){return h('div',{},a.estimationNotes?note('推定の根拠：'+a.estimationNotes):null,(a.sources||[]).length?h('div',{},h('h3',{},'公式情報として参照したページ'),h('p',{class:'muted'},'店舗・メニュー・サイズが合っているか、リンク先をご確認ください。'),a.sources.map(s=>h('p',{},h('a',{href:s.url,target:'_blank',rel:'noopener noreferrer'},s.title||s.url)))):null);}
function foodRow(log,action){return h('button',{type:'button',class:'food-row',onClick:safe(action)},h('span',{class:'food-dot'},'◒'),h('span',{class:'food-info'},h('strong',{},log.name),h('small',{},amountText(log.amount)+' · '+fmt(log.nutrientSnapshot.energy?.value,0)+' kcal · P '+fmt(log.nutrientSnapshot.protein?.value)+' g')),h('span',{class:'plus','aria-hidden':true},'＋'));}
function homeView(){const logs=todayLogs(),total=aggregate(logs),energy=total.energy.value,remaining=energy===null?null:goals.energy.target-energy,protein=total.protein.value;const ring=document.createElementNS('http://www.w3.org/2000/svg','svg');ring.setAttribute('class','ring');ring.setAttribute('viewBox','0 0 120 120');ring.setAttribute('aria-hidden','true');for(const cls of ['track','value']){const c=document.createElementNS('http://www.w3.org/2000/svg','circle');for(const [k,v] of Object.entries({cx:60,cy:60,r:51,class:cls}))c.setAttribute(k,v);if(cls==='value'){c.style.strokeDasharray='320.44';c.style.strokeDashoffset=String(320.44*(1-Math.min(1,(energy||0)/goals.energy.target)));}ring.append(c);}
 const hero=h('section',{class:'card hero'},h('p',{class:'eyebrow'},'TODAY’S BALANCE'),h('div',{class:'energy-layout'},h('div',{},h('div',{class:'energy-label'},remaining===null?'カロリー不明':remaining<0?'目標より':total.energy.partial?'判明分から あと':'あと'),h('div',{class:'energy-number'},fmt(remaining===null?null:Math.abs(remaining),0),h('small',{},'kcal')),h('p',{class:'energy-meta'},remaining<0?'オーバー · 摂取 '+fmt(energy,0)+' kcal':'摂取 '+fmt(energy,0)+' / '+fmt(goals.energy.target,0)+' kcal')),ring),h('div',{class:'hero-foot'},h('span',{},logs.length?(total.energy.partial?('不明なカロリーは含まれていません'+(total.energy.estimated?'・推定を含む':'')):(total.energy.estimated?'今日の集計は推定を含む':'今日の食事を記録しています')):'今日の食事を記録しましょう'),h('span',{},logs.length+' 件')));
 const pbar=h('div',{class:'bar'},h('span'));pbar.firstChild.style.width=Math.min(100,(protein||0)/goals.protein.target*100)+'%';const pcard=card(h('div',{class:'card-head'},h('h2',{},'たんぱく質'),pill(protein===null?'不明':protein>=goals.protein.target?'目標達成':'あと '+fmt(goals.protein.target-protein)+' g')),h('div',{class:'protein-value'},fmt(protein),h('small',{},' / '+fmt(goals.protein.target)+' g')),pbar,h('p',{class:'muted'},total.protein.partial?('判明した分だけを表示しています。'+(total.protein.estimated?'推定を含む':'')):(total.protein.estimated?'推定を含む':'毎日の目標を、少しずつ。')));
 const nutrients=DEFINITIONS.filter(d=>!['energy','protein','sodium','sugar'].includes(d.id)).sort((a,b)=>{const rank=d=>{const s=statusOf(d.id,total[d.id].value,goals);return ['high','near'].includes(s.kind)?-2:s.kind==='unknown'?3:s.ratio??3;};return rank(a)-rank(b);}).slice(0,4);
 const balance=card(h('div',{class:'card-head'},h('h2',{},'栄養バランス'),link('すべて見る →','#nutrients')),logs.length?nutrients.map(d=>nutrientRow(d,total)):empty('食事を記録すると、栄養バランスが表示されます。'));
 const action=h('section',{class:'card action-card'},h('h2',{},'今日のひとさじを記録'),h('p',{},'商品も、手づくりの料理も。',h('br'),'写真から栄養を読み取ります。'),link([h('span',{class:'camera-icon'}),'食事を撮影する'],'#capture','primary wide camera-action'),h('div',{class:'row'},link('食品を選んで記録','#foods'),btn('外食を記録',()=>{capture=null;analysis=null;return newRestaurant();},'secondary')));
 const recent=[...state.intakeLogs].sort((a,b)=>b.consumedAt.localeCompare(a.consumedAt)).filter((l,i,a)=>a.findIndex(x=>x.productId===l.productId)===i).slice(0,4);
 return [title('今日の栄養','DAILY NUTRITION',h('span',{class:'date'},new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'short'}).format(new Date()))),backupReminder(),!hasKey()?note(h('div',{class:'row spread'},h('span',{},'写真解析には、APIキーの設定が必要です。'),link('初期設定へ →','#settings'))):null,state.pendingCaptures.length?note(h('div',{class:'row spread'},h('span',{},'未完了の入力 '+state.pendingCaptures.length+' 件'),link('続きから','#capture'))):null,h('div',{class:'grid'},h('div',{class:'stack'},hero,pcard),h('div',{class:'stack'},action,balance)),h('section',{class:'section'},btn('✧  何を食べればいい？',()=>navigate('recommend'),'secondary wide')),h('section',{class:'section'},h('div',{class:'card-head'},h('h2',{},'最近の商品'),h('span',{class:'muted'},'前回と同じ量を、ワンタップ')),recent.length?h('div',{class:'recent-list'},recent.map(l=>foodRow(l,()=>repeatLog(l)))):card(empty('よく食べるものが、ここに並びます。'))),h('section',{class:'section'},h('div',{class:'card-head'},h('h2',{},'今日の記録'),h('span',{class:'muted'},logs.length+' 件')),logs.length?h('div',{class:'log-list'},[...logs].sort((a,b)=>b.consumedAt.localeCompare(a.consumedAt)).map(logView)):card(empty('まだ記録はありません。最初の食事を撮ってみましょう。'))),h('p',{class:'footer-note'},'記録はこの端末だけに保存されます。定期的にバックアップしましょう。')];}
function logView(log){const time=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'}).format(new Date(log.consumedAt));return h('div',{class:'food-row'},h('span',{class:'food-info'},h('strong',{},log.name),h('small',{},time+' · '+amountText(log.amount)+' · '+fmt(log.nutrientSnapshot.energy.value,0)+' kcal')),btn('詳細',()=>showLog(log),'text-btn'));}
function nutrientTable(values,sources=false){return h('table',{class:'nutrition-table'},h('thead',{},h('tr',{},h('th',{},'栄養素'),h('th',{},'量'),h('th',{},sources?'由来':'判定'))),h('tbody',{},DEFINITIONS.filter(d=>d.id!=='sodium').map(d=>{const n=values[d.id],s=statusOf(d.id,n?.value??null,goals);return h('tr',{},h('td',{},d.label),h('td',{},fmt(n?.value??null)+' '+d.unit,n?.partial?h('small',{},'（一部不明）'):null),h('td',{},sources?({declared:'表示値',published:'公式掲載値',calculated:n?.origin==='published'?'公式値の換算':'換算値',estimated:'推定値'}[n?.source]||'不明'):goals[d.id]?[s.label,n?.partial?'判明分のみ':'',n?.estimated?'推定を含む':''].filter(Boolean).join('・'):'—'));})));}
function showLog(log){dialogBody.replaceChildren(h('h2',{},log.name),h('p',{class:'muted'},log.dayKey+' · '+amountText(log.amount)),nutrientTable(log.nutrientSnapshot,true),sourceNotes(state.productVersions.find(v=>v.id===log.productVersionId)?.analysis||{}),h('div',{class:'row'},btn('閉じる',()=>dialog.close()),btn('記録を削除',async()=>{dialog.close();if(await ask('この食事記録を削除しますか？','商品情報は残ります。')){await db.remove('intakeLogs',log.id);await refresh();render();toast('記録を削除しました');}},'danger')));dialog.showModal();}
function nutrientsView(){const total=aggregate(todayLogs());return [title('栄養素の一覧','TODAY’S NUTRIENTS'),link('← 今日へ','#home'),card(h('p',{class:'muted'},'達成済みも含めた全栄養素です。推定値も合計・判定に含めます。不明な値は0として扱いません。上限比100%は上限に到達した状態です。'),DEFINITIONS.map(d=>nutrientRow(d,total)))];}
async function newRestaurant(){capture={id:crypto.randomUUID(),createdAt:stamp(),status:'captured',images:[],attempts:0,analysis:null,mode:'restaurant',query:'',search:true};await db.put('pendingCaptures',capture);await refresh();navigate('capture');}
function restaurantInputs(){
 const query=h('textarea',{value:capture.query||'',placeholder:'例：○○食堂、焼き魚定食、ご飯は普通盛り',maxlength:2000,'aria-label':'店名・メニュー名',disabled:analyzing,onChange:()=>render(),onInput:safe(async e=>{capture.query=e.target.value;capture.attempts=0;capture.analysis=null;capture.status='captured';await db.put('pendingCaptures',capture);})});
 const search=h('input',{type:'checkbox',checked:capture.search!==false,disabled:analyzing,onChange:safe(async e=>{capture.search=e.target.checked;capture.attempts=0;capture.analysis=null;capture.status='captured';await db.put('pendingCaptures',capture);render();})});
 return card(h('h2',{},'外食の店名・メニュー'),label('写真だけでも、文字入力だけでも記録できます',query),h('label',{class:'row'},search,'公式情報をWeb検索する'),h('p',{class:'muted'},'検索は最大2回、検索料金は最大0.02米ドル＋解析の通信量に応じた料金です。検索と整理で2回APIを呼びます。検索を外すと追加検索なしで推定します。'),h('p',{class:'muted'},'店名・メニュー名・写真をAnthropicへ送ります。検索語は検索サービスでも処理されます。1回の解析は1品・1セットにしてください。'));
}
async function newCapture(files){if(analyzing)return;const selected=Array.from(files);if(!selected.length)return;if((capture?.images.length||0)+selected.length>5)throw new Error('写真は合計5枚まで追加できます。');const photos=[];for(const file of selected)photos.push(await resizePhoto(file));if(!capture)capture={id:crypto.randomUUID(),createdAt:stamp(),status:'captured',images:[],attempts:0,analysis:null};capture.images.push(...photos);capture.status='captured';capture.attempts=0;capture.analysis=null;analysis=null;await db.put('pendingCaptures',capture);await refresh();render();}
function photoInput(camera=false){return h('input',{type:'file',accept:'image/*',multiple:!camera,capture:camera?'environment':null,class:'sr-only','aria-label':camera?'カメラで撮影':'写真を選ぶ',onChange:safe(async e=>{const files=Array.from(e.target.files);e.target.value='';await newCapture(files);})});}
function captureView(){const camera=photoInput(true),library=photoInput(),content=card(camera,library,h('div',{class:'dropzone'},h('span',{class:'camera-icon'}),h('h2',{},capture?.images.length?'別の面も撮れます':'食事を撮影する'),h('p',{class:'muted'},'商品名や栄養成分表示が、はっきり写るように。',h('br'),'料理の写真も、そのままで大丈夫です。'),h('div',{class:'row'},btn('カメラで撮影',()=>camera.click(),'primary',{disabled:analyzing}),btn('写真を選ぶ',()=>library.click(),'secondary',{disabled:analyzing}))));
 if(capture?.mode==='restaurant')content.prepend(restaurantInputs());
 if(capture){content.append(h('div',{class:'thumbnails'},capture.images.map((src,i)=>h('div',{class:'thumb'},h('img',{src,alt:'解析用の写真 '+(i+1)}),btn('×',async()=>{capture.images.splice(i,1);capture.attempts=0;capture.analysis=null;capture.status='captured';await db.put('pendingCaptures',capture);render();},'',{'aria-label':'写真 '+(i+1)+' を削除',disabled:analyzing})))));if(capture.status==='failed')content.append(note(capture.error||'解析に失敗しました。','error'));if(capture.analysis&&capture.status==='awaiting_confirmation')content.append(btn('確認画面へ',()=>{analysis=capture.analysis;amount=structuredClone(analysis.consumedAmountCandidate);consumedAt=capture.createdAt;navigate('review');},'primary wide'));else if(analyzing)content.append(h('div',{class:'loading'}),h('p',{class:'muted'},'入力を解析しています。外食検索には数分かかる場合があります。'));else{content.append(btn(navigator.onLine?(capture.attempts?'もう一度解析する':capture.mode==='restaurant'?(capture.search!==false?'公式情報を検索して解析':'検索せず推定する'):'この写真を解析する'):'ネット接続後に解析',runAnalysis,'primary wide',{disabled:!navigator.onLine||capture.attempts>=2}));if(capture.attempts>=2)content.append(note('再試行は終了しました。写真または店名・メニューを修正してください。'));}content.append(h('p',{class:'muted'},'解析時に写真をAnthropicへ送信します。記録保存後、この端末の写真データは削除します。'),btn('この入力を破棄',async()=>{if(await ask('この入力を破棄しますか？','未保存の解析結果も破棄します。')){await db.remove('pendingCaptures',capture.id);capture=null;analysis=null;await refresh();render();}},'text-btn',{disabled:analyzing}));}
 const pending=state.pendingCaptures.filter(p=>p.id!==capture?.id);return [title('食事を記録','PHOTO NOTE'),h('div',{class:'row section'},btn('通常の写真を新しく記録',()=>{capture=null;analysis=null;render();},'secondary',{disabled:analyzing}),btn('外食を新しく記録',newRestaurant,'secondary',{disabled:analyzing})),!hasKey()?note(h('div',{},'写真解析にはAPIキーが必要です。 ',link('設定へ','#settings'))):null,content,pending.length?card(h('h2',{},'保留中の入力'),pending.map(p=>h('div',{class:'row spread pending'},h('span',{class:'muted'},dayKey(p.createdAt)+' · '+(p.mode==='restaurant'?(p.query||'外食の入力')+' · ':'')+p.images.length+'枚'),btn('続きから',()=>{capture=p;analysis=p.analysis;render();},'secondary',{disabled:analyzing})))):null];}
function findFood(name){const aliases={'ご飯':'精白米 うるち米','白米':'精白米 うるち米','ゆで卵':'鶏卵 全卵 ゆで','牛乳':'普通牛乳','ほうれん草':'ほうれんそう','小松菜':'こまつな','鮭':'しろさけ','鶏むね肉':'にわとり むね','鶏肉':'にわとり','納豆':'糸引き納豆'};let q=name;for(const [a,b]of Object.entries(aliases))q=q.replace(a,b);const words=q.replace(/[約\d.g（）()]/g,' ').split(/[\s　]+/).filter(Boolean);if(!words.length)return null;const matches=foods.filter(f=>words.every(w=>f.name.includes(w)));return matches.length===1?matches[0]:matches.find(f=>f.recommendation)||null;}
async function runAnalysis(){if(analyzing||!capture||capture.attempts>=2)return;if(!hasKey())throw new Error('設定でAPIキーを入力してください。');if(!navigator.onLine)throw new Error('ネット接続後に解析できます。');analyzing=true;capture.attempts++;capture.status='uploading';render();try{await db.put('pendingCaptures',capture);analysis=await analyze(capture.images,settings,{mode:capture.mode,query:capture.query,search:capture.search});for(const c of analysis.estimatedComponents){const food=findFood(c.name);c.foodId=food?.id||null;if(food)c.confidence=Math.min(.8,c.confidence);}capture.analysis=analysis;capture.status='awaiting_confirmation';capture.error=null;await db.put('pendingCaptures',capture);amount=structuredClone(analysis.consumedAmountCandidate);consumedAt=capture.createdAt;navigate('review');}catch(e){capture.status='failed';capture.error=e.message;try{await db.put('pendingCaptures',capture);}catch{}toast(e.message);}finally{analyzing=false;await refresh();render();}}
function reviewView(){if(!analysis)return [title('内容の確認','REVIEW'),empty('先に写真を解析するか、食品を選んでください。'),link('撮影へ','#capture','primary')];if(['unreadable','multiple_items','unknown'].includes(analysis.analysisType)||analysis.needsMoreImages)return [title('写真を確認してください','REVIEW'),note(analysis.analysisType==='multiple_items'?'複数の商品が写っています。商品を1つずつ撮影してください。':'栄養成分表示をもう少し近くから撮ってください。','warning'),card(analysis.warnings.map(w=>h('p',{},w)),btn('写真を追加・撮り直す',()=>navigate('capture'),'primary'))];
 let nutrients,error;try{nutrients=snapshot(analysis,amount,foods);}catch(e){error=e.message;}
 return [title('これで記録しますか？','REVIEW & SAVE'),card(pill(analysis.analysisType==='packaged_food'?'市販品':'料理・食品'),h('h2',{class:'review-title'},analysis.productName),h('p',{class:'muted'},analysis.manufacturer||'食品の内容を確認してください'),h('div',{class:'review-macro'},fmt(nutrients?.energy.value??null,0),h('small',{},' kcal')),h('p',{},'たんぱく質 '+fmt(nutrients?.protein.value??null)+' g'),error?note(error,'warning'):null,analysis.warnings.length?note(analysis.warnings.join(' '),'warning'):null,(analysis.estimatedComponents.length||analysis.estimatedNutrients?.length)?h('p',{class:'muted'},'推定を含みます。食材と量は「修正」で確認できます。'):null,sourceNotes(analysis),h('details',{},h('summary',{},'全栄養値と由来を確認'),nutrients?nutrientTable(nutrients,true):null),h('h3',{},'食べた量'),h('div',{class:'row amount-chips'},[['全部',1],['半分',.5],['1/3',1/3]].map(([text,v])=>btn(text,()=>{amount={value:v,unit:'package'};render();},amount.unit==='package'&&amount.value===v?'selected':''))),amountForm(),h('div',{class:'row'},btn('OK・記録する',saveReview,'primary',{disabled:!!error||saving}),btn('修正',()=>{document.querySelector('#edit-analysis').open=true;document.querySelector('#edit-analysis').scrollIntoView({behavior:'smooth',block:'start'});})),h('p',{class:'muted'},'表示・公式値を優先し、未掲載は推定で補います。推定できない成分のみ不明で保存します。')),card(h('details',{id:'edit-analysis'},h('summary',{},'名前・表示値・食材を修正'),editAnalysisForm()))];}
function amountForm(){const val=number(amount.value,{'aria-label':'食べた量',min:.001}),unit=unitSelect(amount.unit);unit.setAttribute('aria-label','食べた量の単位');const update=()=>{amount={value:inputValue(val),unit:unit.value};render();};val.addEventListener('change',update);unit.addEventListener('change',update);const time=h('input',{type:'datetime-local',value:localTime(consumedAt||stamp()),'aria-label':'食べた日時（日本時間）',onChange:e=>{const d=new Date(e.target.value+':00+09:00');if(Number.isFinite(d.getTime()))consumedAt=d.toISOString();}});return h('div',{},h('div',{class:'form-grid section'},label('量',val),label('単位',unit)),label('食べた日時（日本時間）',time));}
const unitSelect=value=>h('select',{},Object.entries(units).map(([v,t])=>h('option',{value:v,selected:value===v},t)));
function editAnalysisForm(){const draft=structuredClone(analysis),name=h('input',{value:draft.productName,required:true}),manufacturer=h('input',{value:draft.manufacturer}),basisV=number(draft.nutritionBasis.value,{min:.001}),netV=number(draft.netAmount.value,{min:.001}),basisU=unitSelect(draft.nutritionBasis.unit),netU=unitSelect(draft.netAmount.unit),ingredients=h('textarea',{value:draft.ingredients.join('、')}),cooking=h('input',{value:draft.cookingMethod}),componentList=h('div');
 function components(){componentList.replaceChildren(...draft.estimatedComponents.map((c,i)=>{const nameInput=h('input',{value:c.name,'aria-label':'食材名',onChange:e=>c.name=e.target.value}),grams=number(c.grams,{'aria-label':'食材の推定重量 g',onChange:e=>c.grams=inputValue(e.target)}),selected=foods.find(f=>f.id===c.foodId);return h('div',{class:'notice'},h('div',{class:'form-grid'},label('食材名',nameInput),label('基準量中の重量 g（不明は空欄）',grams)),h('p',{class:'muted'},selected?'成分表：'+selected.name:'成分表に未照合・栄養値は不明'),h('div',{class:'row'},btn('成分表を選ぶ',()=>chooseFood(food=>{c.foodId=food.id;c.confidence=Math.min(c.confidence,.8);components();}),'text-btn'),btn('食材を削除',()=>{draft.estimatedComponents.splice(i,1);components();},'text-btn')));}));}components();
 const nutrientInputs=new Map(),nutrientFields=h('details',{},h('summary',{},'栄養成分表示を修正（基準量あたり）'),h('p',{class:'muted'},'包装に書かれた値だけを入力してください。不明は空欄にします。'),h('div',{class:'goal-list'},DEFINITIONS.map(d=>{const n=draft.declaredNutrients.find(n=>n.id===d.id),input=number(n?.value??null),unit=h('select',{},[...new Set([d.unit,...(['g','mg','µg'].includes(d.unit)?['g','mg','µg']:[])])].map(u=>h('option',{value:u,selected:(n?.unit||d.unit)===u},u)));nutrientInputs.set(d.id,{input,unit});return h('div',{class:'goal-row'},h('label',{},d.label),h('div',{class:'row'},input,unit));})));
 const estimateInputs=new Map(),estimateFields=h('details',{},h('summary',{},'推定栄養値を修正（基準量あたり）'),h('p',{class:'muted'},'推定値を表示値と区別して保存します。表示値・公式掲載値がある栄養素はそちらを優先します。成分表で食材と重量がそろう栄養素は成分表から再計算します。'),h('div',{class:'goal-list'},DEFINITIONS.map(d=>{const n=draft.estimatedNutrients?.find(n=>n.id===d.id),v=n?.value===null||!n?null:normalizeUnit(n.value,n.unit,d.unit),input=number(v,{'aria-label':d.label+' 推定値'});estimateInputs.set(d.id,input);return h('div',{class:'goal-row'},h('label',{},d.label+' '+d.unit),input);}))),estimationNotes=h('textarea',{value:draft.estimationNotes||''});
 return h('form',{onSubmit:safe(async e=>{e.preventDefault();draft.productName=name.value.trim();draft.manufacturer=manufacturer.value.trim();draft.nutritionBasis={value:inputValue(basisV),unit:basisU.value};draft.netAmount={value:inputValue(netV),unit:netU.value};draft.ingredients=ingredients.value.split(/[、,\n]/).filter(Boolean);draft.cookingMethod=cooking.value;draft.declaredNutrients=Array.from(nutrientInputs,([id,{input,unit}])=>({id,value:inputValue(input),unit:unit.value})).filter(n=>n.value!==null);draft.estimatedNutrients=Array.from(estimateInputs,([id,input])=>({id,value:inputValue(input),unit:DEFINITIONS.find(d=>d.id===id).unit})).filter(n=>n.value!==null);draft.estimationNotes=estimationNotes.value;validateAnalysis(draft);analysis=draft;if(capture){capture.analysis=analysis;await db.put('pendingCaptures',capture);}render();toast('修正しました');})},label('商品・料理名',name),label('メーカー',manufacturer),h('div',{class:'form-grid'},label('栄養表示の基準量',basisV),label('基準量の単位',basisU),label('1包装・1皿の内容量',netV),label('内容量の単位',netU)),label('原材料',ingredients),label('調理方法',cooking),h('h3',{},'推定食材'),h('p',{class:'muted'},'重量は「栄養表示の基準量」に含まれる量です。原材料だけでは配合量を確定できません。'),componentList,btn('＋ 食材を追加',()=>{draft.estimatedComponents.push({name:'',foodId:null,grams:null,confidence:.5});components();},'text-btn'),nutrientFields,estimateFields,label('推定の根拠・仮定',estimationNotes),h('button',{type:'submit',class:'primary section'},'修正を反映'));}
async function saveReview(){if(saving)return;saving=true;render();try{validateAnalysis(analysis);const nutrients=snapshot(analysis,amount,foods),now=stamp(),name=analysis.productName.trim();let product=state.products.find(p=>p.name===name&&p.manufacturer===analysis.manufacturer.trim()),version;if(product){const versions=state.productVersions.filter(v=>v.productId===product.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));version=versions.find(v=>versionFingerprint(v.analysis)===versionFingerprint(analysis));if(!version&&versions[0]&&majorChange(versions[0].analysis,analysis)){const choice=await ask('登録済みの商品と内容が異なります','リニューアルされた可能性があります。以前の記録は変更されません。',[['キャンセル',false],['別の商品として登録','separate'],['新版として登録','version']]);if(!choice)return;if(choice==='separate')product=null;}}
 if(product&&isDuplicate(state.intakeLogs,product.id,consumedAt)&&!await ask('もう1つ食べましたか？','少し前にも同じ商品を記録しています。'))return;if(!product)product={id:crypto.randomUUID(),name,manufacturer:analysis.manufacturer.trim(),createdAt:now};if(!version)version={id:crypto.randomUUID(),productId:product.id,createdAt:now,analysis:structuredClone(analysis),foodDatabaseVersion:foodDB.sourceVersion};const log={id:crypto.randomUUID(),productId:product.id,productVersionId:version.id,name,consumedAt:consumedAt||now,dayKey:dayKey(consumedAt||now),amount:structuredClone(amount),nutrientSnapshot:nutrients};await db.saveIntake(product,version,log,capture?.id);capture=null;analysis=null;amount=null;await refresh();navigate('home');undoToast(log);}finally{saving=false;render();}}
function undoToast(log){toast('食事を記録しました',{label:'元に戻す',run:safe(async()=>{await db.remove('intakeLogs',log.id);await refresh();render();toast('登録を取り消しました');})});}
async function repeatLog(previous){if(saving)return;saving=true;try{if(isDuplicate(state.intakeLogs,previous.productId)&&!await ask('もう1つ食べましたか？','少し前にも同じ商品を記録しています。'))return;const time=stamp(),log={...structuredClone(previous),id:crypto.randomUUID(),consumedAt:time,dayKey:dayKey(time)};await db.saveIntake(null,null,log);await refresh();render();undoToast(log);}finally{saving=false;}}

function foodSearchControls(select){const input=h('input',{type:'search',placeholder:'例：納豆、ヨーグルト、こまつな','aria-label':'食品を検索'}),results=h('div',{class:'filter-list'});const update=()=>{const terms=input.value.trim().split(/[\s　]+/).filter(Boolean),list=foods.filter(f=>terms.length?terms.every(t=>f.name.includes(t)):f.recommendation).slice(0,45);results.replaceChildren(...list.map(f=>h('button',{class:'food-row',type:'button',onClick:safe(()=>select(f))},h('span',{class:'food-info'},h('strong',{},f.name),h('small',{},'100gあたり '+fmt(f.nutrients.energy,0)+' kcal')),h('span',{class:'plus'},'＋'))));if(!list.length)results.append(empty('一致する食品がありません。ひらがなや短い食品名で検索してください。'));};input.addEventListener('input',update);update();return h('div',{},label('食品名',input),results);}
function chooseFood(callback){dialogBody.replaceChildren(h('h2',{},'食品成分表から選ぶ'),foodSearchControls(food=>{callback(food);dialog.close();}),btn('閉じる',()=>dialog.close(),'text-btn'));dialog.showModal();}
function foodsView(){return [title('食品を選んで記録','FOOD COMPOSITION'),card(h('p',{class:'muted'},'食品成分表 '+fmt(foods.length,0)+' 品目。標準的な食品の推定値です。'),foodSearchControls(food=>{capture=null;analysis=foodAnalysis(food,food.servingGrams||100);amount=structuredClone(analysis.consumedAmountCandidate);consumedAt=stamp();navigate('review');})),h('p',{class:'footer-note'},'出典：'+foodDB.sourceName+' '+foodDB.sourceVersion)];}
function historyView(){const days=daysBack(historyDays),logs=state.intakeLogs.filter(l=>days.includes(l.dayKey)),total=aggregate(logs),recorded=new Set(logs.map(l=>l.dayKey)).size,avg=Object.fromEntries(Object.entries(total).map(([id,n])=>[id,{...n,value:n.value===null||!recorded?null:n.value/recorded}])),chart=h('div',{class:'chart','aria-label':'日別摂取カロリー'});for(const key of days){const rows=logs.filter(l=>l.dayKey===key),sum=aggregate(rows).energy,b=h('div',{class:'chart-bar',title:key+' '+(rows.length?fmt(sum.value,0)+' kcal':'未記録')});b.style.height=rows.length?Math.max(2,Math.min(100,(sum.value||0)/goals.energy.target*90))+'%':'2px';if(!rows.length)b.style.background='#e4e8df';chart.append(h('div',{class:'chart-col'},b,h('small',{},key.slice(8))));}
 const trends=DEFINITIONS.filter(d=>goals[d.id]&&d.id!=='energy').map(d=>{let low=0,high=0,known=0;for(const key of days){const rows=logs.filter(l=>l.dayKey===key);if(!rows.length)continue;const n=aggregate(rows)[d.id];if(n.value===null||n.partial)continue;known++;const s=statusOf(d.id,n.value,goals);if(s.kind==='low')low++;if(s.kind==='high')high++;}return {d,low,high,known};}).filter(t=>t.known>=Math.min(historyDays,3)&&(t.low/t.known>=.6||t.high/t.known>=.6));
 return [title('食事のふりかえり','YOUR HISTORY'),h('div',{class:'segmented'},[[1,'今日'],[7,'7日'],[30,'30日']].map(([n,t])=>btn(t,()=>{historyDays=n;render();},historyDays===n?'selected':''))),h('section',{class:'section'},card(h('div',{class:'card-head'},h('h2',{},'記録日の平均'),pill(recorded+' / '+historyDays+' 日記録')),h('div',{class:'summary-numbers'},h('div',{},h('span',{class:'muted'},'カロリー'),h('strong',{},fmt(avg.energy.value,0)),h('small',{},'kcal / 日')),h('div',{},h('span',{class:'muted'},'たんぱく質'),h('strong',{},fmt(avg.protein.value)),h('small',{},'g / 日'))),chart,h('p',{class:'muted'},'推定を含む集計・判定です。未記録日は平均に含めません。不明な成分は判明分のみ集計します。'))),h('section',{class:'section'},card(h('h2',{},'続いている傾向'),trends.length?trends.map(t=>h('div',{class:'nutrient-line nutrient'},h('span',{},t.d.label),pill((t.high/t.known>=.6?'多め':'不足')+' '+Math.max(t.low,t.high)+' / '+t.known+'日（推定を含む）','warn'))):empty('記録が増えると、続いている不足や摂りすぎを確認できます。'))),h('section',{class:'section'},card(h('h2',{},'栄養素の平均・達成率'),DEFINITIONS.filter(d=>goals[d.id]).map(d=>h('div',{},nutrientRow(d,avg),h('small',{class:'muted'},fmt(avg[d.id].value)+' '+d.unit+' / 日'))))),h('section',{class:'section'},h('h2',{},'期間中の記録'),logs.length?[...days].reverse().map(key=>{const rows=logs.filter(l=>l.dayKey===key);return rows.length?card(h('h3',{},key),rows.map(logView)):null;}):empty('この期間の記録はありません。'))];}
function recommendView(){const r=recommend(state,goals,foods,filter);return [title('何を食べればいい？','A LITTLE SUGGESTION'),h('p',{class:'muted'},'今日の残りカロリーと栄養、直近7日の記録から提案します。推定を含む値で判定します。'),h('div',{class:'row amount-chips'},[['all','すべて'],['store','最近の商品'],['home','家'],['low','低カロリー'],['small','少量'],['sweet','甘い'],['salty','しょっぱい']].map(([v,t])=>btn(t,()=>{filter=v;render();},filter===v?'selected':''))),h('section',{class:'section'},r.reason?card(empty(r.reason)):h('div',{class:'stack'},note('残り '+fmt(r.remaining,0)+' kcal 以内の候補です。'),r.items.map(c=>card(h('div',{class:'card-head'},pill(c.source),h('span',{class:'muted'},amountText(c.amount))),h('h2',{},c.name),h('p',{},fmt(c.snapshot.energy.value,0)+' kcal · たんぱく質 '+fmt(c.snapshot.protein.value)+' g'),h('p',{class:'muted'},c.benefits.length?c.benefits.join('・')+'を補えます。':'残りカロリーに収まる候補です。'),btn('内容を確認',()=>{capture=null;analysis=structuredClone(c.analysis||state.productVersions.find(v=>v.id===c.log.productVersionId).analysis);amount=structuredClone(c.amount);consumedAt=stamp();navigate('review');},'secondary wide'))))),h('p',{class:'footer-note'},'候補は1品ずつの評価です。記録すると次の候補を再計算します。')];}

function settingsView(){const keyInput=h('input',{type:'password',autocomplete:'new-password',placeholder:hasKey()?'登録済み（変更するときだけ入力）':'APIキーを貼り付け','aria-label':'Claude APIキー'}),model=h('input',{value:settings.model,required:true,pattern:'claude-[a-z0-9-]+','aria-label':'モデルID'}),structured=h('input',{type:'checkbox',checked:settings.structuredOutput});
 const keyForm=h('form',{onSubmit:safe(async e=>{e.preventDefault();if(!/^claude-[a-z0-9-]+$/.test(model.value))throw new Error('モデルIDを確認してください。');if(keyInput.value.trim())setKey(keyInput.value);keyInput.value='';settings={id:'preferences',model:model.value,structuredOutput:structured.checked};await db.put('settings',settings);render();toast('解析設定を保存しました');})},label('Claude APIキー',keyInput),h('p',{class:'muted'},hasKey()?'APIキーはこの端末に登録されています。':'APIキーは端末内にのみ保存し、バックアップには含めません。'),label('モデルID',model),h('label',{class:'row muted'},structured,'構造化出力を使う（推奨）'),h('div',{class:'row section'},h('button',{type:'submit',class:'primary'},'解析設定を保存'),btn('キーを削除',async()=>{if(await ask('APIキーを削除しますか？','食事の記録は残ります。')){deleteKey();render();toast('APIキーを削除しました');}},'text-btn')));
 const goalInputs=new Map(),goalForm=h('form',{onSubmit:safe(async e=>{e.preventDefault();const next=structuredClone(goals);for(const [id,inputs]of goalInputs){next[id].target=inputValue(inputs[0]);if(inputs[1])next[id].upper=inputValue(inputs[1]);}validateGoals(next);await db.put('settings',{id:'goals',value:next});await refresh();render();toast('目標値を保存しました');})},h('div',{class:'goal-list'},DEFINITIONS.filter(d=>goals[d.id]).map(d=>{const g=goals[d.id],first=number(g.target,{min:.001,required:true,'aria-label':d.label+' 目標'}),second=g.upper?number(g.upper,{min:.001,required:true,'aria-label':d.label+' 上限'}):null;goalInputs.set(d.id,[first,second]);return h('div',{class:'goal-row'},h('label',{},d.label+'（'+{minimum:'以上',maximum:'上限',range:'範囲'}[g.mode]+'）'),h('div',{class:'row'},first,second?'〜':null,second,h('small',{},['fat','carbohydrate','saturatedFat'].includes(d.id)?'% エネルギー':d.unit)));})),h('button',{type:'submit',class:'primary section'},'目標を保存'));
 const restore=h('input',{type:'file',accept:'.json,application/json',class:'sr-only','aria-label':'バックアップJSONを選択',onChange:safe(async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;const backup=await readBackup(file);if(await ask('現在の記録を置き換えますか？',backup.intakeLogs.length+'件の食事記録を復元します。現在の記録・保留写真は置き換えられます。必要なら先に書き出してください。')){await db.replaceData(backup);capture=null;analysis=null;await refresh();render();toast('バックアップから復元しました');}})});
 return [title('設定','PREFERENCES'),card(h('h2',{},'端末の保存状態'),h('p',{},persistence.label),btn('保存保護をリクエスト',async()=>{persistence=await storageStatus(true);render();},'secondary'),h('p',{class:'muted'},'保存保護が許可されても、手動削除などによる消失を防ぐ保証はありません。バックアップも残してください。'),h('p',{class:'muted'},'保存先：'+location.origin+' / '+(navigator.standalone||matchMedia('(display-mode: standalone)').matches?'ホーム画面アプリ':'ブラウザ')),h('p',{class:'muted'},'記録 '+state.intakeLogs.length+'件・APIキー '+(hasKey()?'登録済み':'未登録'))),card(h('h2',{},'iPhoneでは最初にホーム画面へ'),h('ol',{class:'muted'},h('li',{},'Safariでこのアプリを開く'),h('li',{},'共有 →「ホーム画面に追加」を選ぶ'),h('li',{},'ホーム画面から起動して、APIキーを入力する')),h('p',{class:'muted'},'Safariとホーム画面版で記録が分かれる場合があります。移行にはJSONバックアップを使ってください。')),h('section',{class:'section'},card(h('h2',{},'写真の解析'),h('p',{class:'muted'},'Anthropic Consoleで月間利用上限を低めに設定してから利用してください。'),keyForm)),h('section',{class:'section'},card(h('h2',{},'1日の目標'),h('p',{class:'muted'},'初期値は仕様書の指定値です。脂質・炭水化物・飽和脂肪酸はカロリー目標に連動してgに換算します。'),goalForm)),h('section',{class:'section'},card(h('h2',{},'バックアップ'),h('p',{class:'muted'},backupDate()?'最終書き出し：'+new Date(backupDate()).toLocaleString('ja-JP'):'まだ書き出していません'),h('p',{class:'muted'},'写真とAPIキーは含まれません。定期的に端末外にも保存してください。'),restore,h('div',{class:'row'},btn('全データを書き出す',()=>writeBackup(),'primary'),btn('ダウンロードで書き出す',()=>writeBackup(true)),btn('JSONから復元',()=>restore.click())),btn('食事データをすべて削除',async()=>{if(await ask('すべての食事データを削除しますか？','先にバックアップを書き出してください。商品、記録、保留写真が削除されます。APIキーと目標は残ります。')){await db.transact(['products','productVersions','intakeLogs','pendingCaptures'],tx=>{for(const s of ['products','productVersions','intakeLogs','pendingCaptures'])tx.objectStore(s).clear();});capture=null;analysis=null;await refresh();render();toast('食事データを削除しました');}},'danger section'))),h('section',{class:'section'},card(h('h2',{},'食品成分データ'),h('p',{class:'muted'},foodDB.sourceName+' '+foodDB.sourceVersion+' / '+foods.length+'品目'),h('p',{class:'muted'},'出典データを正規化して同梱しています。微量（Tr）と未測定は不明として扱います。'),link('出典を確認','https://www.mext.go.jp/a_menu/syokuhinseibun/mext_00001.html'))),h('p',{class:'footer-note'},'ひとさじ v1.1 · 個人の食事管理・栄養傾向の把握用')];}

async function start(){try{await refresh();const response=await fetch('./data/food-composition.json');if(!response.ok)throw new Error('食品成分データを読み込めませんでした。');foodDB=await response.json();foods=foodDB.foods;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>toast('オフライン準備ができませんでした。接続中にもう一度開いてください。'));storageStatus(true).then(s=>{persistence=s;if(route==='settings')render();});window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});window.addEventListener('online',render);window.addEventListener('offline',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh().then(render).catch(()=>{});});if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'read_today_nutrition',title:'今日の栄養を確認',description:'この端末の今日の栄養集計を読み取ります。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('入力は空のオブジェクトにしてください。');await refresh();return {day:dayKey(),records:todayLogs().length,totals:aggregate(todayLogs())};}});}catch{/* Optional browser capability. */}}}catch(e){app.replaceChildren(title('起動できませんでした'),note(e.message,'error'),btn('再読み込み',()=>location.reload(),'primary'));}}
start();



