export const DEFINITIONS = [
 ['energy','エネルギー','kcal','maximum',1600],['protein','たんぱく質','g','minimum',80],['fat','脂質','g','range',20,30],['carbohydrate','炭水化物','g','range',50,65],['sugar','糖質','g','info',null],['fiber','食物繊維','g','minimum',22],['n3','n-3系脂肪酸','g','minimum',2.2],['n6','n-6系脂肪酸','g','minimum',11],['saturatedFat','飽和脂肪酸','g','maximum',7],['vitaminA','ビタミンA','µgRAE','minimum',900],['vitaminD','ビタミンD','µg','minimum',9],['vitaminE','ビタミンE','mg','minimum',6.5],['vitaminK','ビタミンK','µg','minimum',150],['b1','ビタミンB1','mg','minimum',1.2],['b2','ビタミンB2','mg','minimum',1.7],['niacin','ナイアシン','mgNE','minimum',16],['b6','ビタミンB6','mg','minimum',1.5],['b12','ビタミンB12','µg','minimum',4],['folate','葉酸','µg','minimum',240],['pantothenicAcid','パントテン酸','mg','minimum',6],['biotin','ビオチン','µg','minimum',50],['vitaminC','ビタミンC','mg','minimum',100],['potassium','カリウム','mg','minimum',3000],['calcium','カルシウム','mg','minimum',750],['magnesium','マグネシウム','mg','minimum',380],['phosphorus','リン','mg','minimum',1000],['iron','鉄','mg','minimum',7.5],['zinc','亜鉛','mg','minimum',9.5],['copper','銅','mg','minimum',.9],['manganese','マンガン','mg','minimum',3.5],['iodine','ヨウ素','µg','minimum',140],['selenium','セレン','µg','minimum',35],['chromium','クロム','µg','minimum',10],['molybdenum','モリブデン','µg','minimum',30],['salt','食塩相当量','g','maximum',7.5],['sodium','ナトリウム','mg','info',null]
].map(([id,label,unit,mode,target,upper])=>({id,label,unit,mode,target,upper}));
export const BY_ID=Object.fromEntries(DEFINITIONS.map(d=>[d.id,d]));
export const DEFAULT_GOALS=Object.fromEntries(DEFINITIONS.filter(d=>d.mode!=='info').map(d=>[d.id,{mode:d.mode,target:d.target,...(d.upper?{upper:d.upper}:{})}]));
export const DEFAULT_SETTINGS={id:'preferences',model:'claude-sonnet-5-5',structuredOutput:true};
export const dayKey=(date=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(date));
export function daysBack(count,from=new Date()){const end=dayKey(from);return Array.from({length:count},(_,i)=>dayKey(new Date(new Date(end+'T12:00:00+09:00').getTime()-(count-1-i)*86400000)));}
export const fmt=(n,digits=1)=>n===null||n===undefined?'不明':new Intl.NumberFormat('ja-JP',{maximumFractionDigits:digits}).format(n);
export function goalFor(id,goals){const g=goals[id];if(!g)return null;const energy=goals.energy.target;if(id==='fat'||id==='saturatedFat')return {...g,target:energy*g.target/100/9,upper:g.upper?energy*g.upper/100/9:undefined};if(id==='carbohydrate')return {...g,target:energy*g.target/100/4,upper:energy*g.upper/100/4};return g;}
export function statusOf(id,value,goals){const g=goalFor(id,goals);if(value===null||!g)return {label:'不明',ratio:null,kind:'unknown'};const ratio=value/g.target;return {ratio,kind:g.mode==='minimum'?(ratio>=1?'good':'low'):g.mode==='maximum'?(ratio>1?'high':ratio>=.8?'near':'good'):(value<g.target?'low':value>g.upper?'high':'good'),label:g.mode==='minimum'?(ratio>=1?'目標達成':'不足'):g.mode==='maximum'?(ratio>1?'上限超過':ratio>=.8?'上限に近い':'上限以内'):(value<g.target?'不足':value>g.upper?'多め':'範囲内')};}
export function normalizeUnit(value,from,to){if(value===null)return null;if(from===to)return value;const scale={g:1,mg:.001,'µg':.000001};if(scale[from]&&scale[to])return value*scale[from]/scale[to];throw new Error('栄養素の単位を確認してください。');}
export function multiplier(analysis,amount){if(!amount||!(amount.value>0)||!Number.isFinite(amount.value))throw new Error('食べた量を入力してください。');const b=analysis.nutritionBasis;if(!b||!(b.value>0))throw new Error('栄養表示の基準量を確認してください。');if(amount.unit===b.unit)return amount.value/b.value;const net=analysis.netAmount;
 if(amount.unit==='package'&&net?.unit===b.unit&&net.value>0)return amount.value*net.value/b.value;
 if(b.unit==='package'&&net?.unit===amount.unit&&net.value>0)return amount.value/net.value/b.value;
 throw new Error('この単位への換算に必要な内容量がありません。表示基準と同じ単位を使うか、内容量を修正してください。');}
export function snapshot(analysis,amount,foods=[]){const factor=multiplier(analysis,amount),result={};for(const d of DEFINITIONS)result[d.id]={value:null,unit:d.unit,source:null,confidence:null};
 // Components are weights for ONE nutritionBasis, never for the consumed amount.
 const components=analysis.estimatedComponents||[];
 for(const d of DEFINITIONS){if(!components.length)continue;let sum=0,complete=true,confidence=1;for(const c of components){const food=foods.find(f=>f.id===c.foodId);const v=food?.nutrients[d.id];if(c.grams===null||v===null||v===undefined){complete=false;break;}sum+=v*c.grams/100;confidence=Math.min(confidence,c.confidence);}if(complete)result[d.id]={value:sum*factor,unit:d.unit,source:'estimated',confidence,foodIds:components.map(c=>c.foodId)};}
 for(const n of analysis.declaredNutrients||[]){if(n.value===null)continue;const d=BY_ID[n.id];if(!d)continue;result[n.id]={value:normalizeUnit(n.value,n.unit,d.unit)*factor,unit:d.unit,source:factor===1?'declared':'calculated',confidence:analysis.confidence};}
 // Salt declarations always win over sodium conversions; never add both.
 const saltDeclared=analysis.declaredNutrients?.some(n=>n.id==='salt'&&n.value!==null);
 const sodiumDeclared=analysis.declaredNutrients?.some(n=>n.id==='sodium'&&n.value!==null);
 if(!saltDeclared&&sodiumDeclared){result.salt={value:result.sodium.value*2.54/1000,unit:'g',source:'calculated',confidence:analysis.confidence};}
 return result;
}
export function aggregate(logs){return Object.fromEntries(DEFINITIONS.map(d=>{const values=logs.map(l=>l.nutrientSnapshot[d.id]?.value??null);const known=values.filter(v=>v!==null);return [d.id,{value:logs.length===0?0:known.length?known.reduce((a,b)=>a+b,0):null,partial:known.length<logs.length,known:known.length,total:logs.length,estimated:logs.some(l=>l.nutrientSnapshot[d.id]?.source==='estimated')}];}));}
export function versionFingerprint(a){return JSON.stringify({name:a.productName.trim(),manufacturer:a.manufacturer.trim(),net:a.netAmount,basis:a.nutritionBasis,nutrients:[...a.declaredNutrients].sort((a,b)=>a.id.localeCompare(b.id)),components:a.estimatedComponents});}
export function majorChange(a,b){if(JSON.stringify(a.netAmount)!==JSON.stringify(b.netAmount)||JSON.stringify(a.nutritionBasis)!==JSON.stringify(b.nutritionBasis))return true;return ['energy','protein','fat','carbohydrate'].some(id=>{const x=a.declaredNutrients.find(n=>n.id===id)?.value??null,y=b.declaredNutrients.find(n=>n.id===id)?.value??null;return x===null||y===null?x!==y:Math.abs(x-y)>Math.max(.1,Math.abs(x)*.05);});}
export function isDuplicate(logs,productId,time=new Date()){return logs.some(l=>l.productId===productId&&Math.abs(new Date(l.consumedAt)-new Date(time))<120000);}
